const $=s=>document.querySelector(s);
let cases=[],charts={},currentPage=1,demo='age';
const PAGE_SIZE=10, cols={date:'Creation Date',classification:'Malaria Classification',facility:'ReportingOrganizationSource',age:'Age',gender:'Gender',nationality:'Nationality',investigation:'Investigation',status:'Investigation Status'};
const months=['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'];
const ageBands=[['0–4',0,4],['5–14',5,14],['15–29',15,29],['30–44',30,44],['45–59',45,59],['60+',60,200]];
function val(r,k){const v=r[cols[k]];return v===undefined||v===null||v===''||v==='N/A'?'غير متوفر':String(v).trim()}
function norm(v){return String(v||'').toLowerCase().trim()}
function malariaType(r){const x=norm(val(r,'classification'));if(x.includes('falciparum')||x.includes('خبيث'))return'Falciparum';if(x.includes('vivax')||x.includes('حميد'))return'Vivax';if(x.includes('malariae'))return'Malariae';if(x.includes('ovale')||x.includes('اوفالي')||x.includes('أوفالي'))return'Ovale';if(x.includes('mix')||x.includes('مختلط'))return'Mix';return null}
function excelDate(v){if(!v||v==='غير متوفر')return null;if(v instanceof Date)return v;if(typeof v==='number')return new Date(Date.UTC(1899,11,30)+v*86400000);const d=new Date(v);return isNaN(d)?null:d}
function dateText(d){return d?new Intl.DateTimeFormat('ar-SA-u-ca-gregory',{day:'numeric',month:'short',year:'numeric'}).format(d):'غير متوفر'}
function group(data,getter){const o={};data.forEach(r=>{const k=getter(r)||'غير متوفر';o[k]=(o[k]||0)+1});return o}
function topGroups(data,getter,n=10){return Object.entries(group(data,getter)).sort((a,b)=>b[1]-a[1]).slice(0,n)}
function pct(a,b){return b?`${Math.round(a/b*100)}%`:'—'}
function selected(id){return [...$(id).querySelectorAll('input:checked')].map(o=>o.value)}
function match(values,item){return !values.length||values.includes(item)}
function filtered(){const mo=selected('#monthFilter'),fa=selected('#facilityFilter'),cl=selected('#classificationFilter'),na=selected('#nationalityFilter'),q=norm($('#searchInput').value);return cases.filter(r=>{const d=excelDate(r[cols.date]),type=malariaType(r),text=[val(r,'facility'),val(r,'nationality'),val(r,'investigation')].join(' ').toLowerCase();return type&&match(mo,d?String(d.getMonth()):'')&&match(fa,val(r,'facility'))&&match(cl,type)&&match(na,val(r,'nationality'))&&(!q||text.includes(q))})}
function draw(id,type,labels,data,colors,reverseX=false){if(charts[id])charts[id].destroy();charts[id]=new Chart($(id),{type,data:{labels,datasets:[{label:'حالات',data,backgroundColor:colors||'#087e7b',borderColor:colors||'#087e7b',borderWidth:type==='line'?2:0,borderRadius:type==='bar'?6:0,fill:type==='line',tension:.35}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:type==='doughnut',position:'bottom',labels:{font:{family:'IBM Plex Sans Arabic'},padding:16}},tooltip:{rtl:true,bodyFont:{family:'IBM Plex Sans Arabic'},titleFont:{family:'IBM Plex Sans Arabic'}}},scales:type==='doughnut'?{}:{x:{reverse:reverseX,grid:{display:false},ticks:{font:{family:'IBM Plex Sans Arabic'}}},y:{beginAtZero:true,ticks:{precision:0,font:{family:'IBM Plex Sans Arabic'}},grid:{color:'#edf1f0'}}}}})}
function render(){const data=filtered(),total=data.length,fal=data.filter(r=>malariaType(r)==='Falciparum').length,viv=data.filter(r=>malariaType(r)==='Vivax').length,dates=data.map(r=>excelDate(r[cols.date])).filter(Boolean).sort((a,b)=>b-a);$('#totalCases').textContent=total.toLocaleString('ar-SA');$('#severeCases').textContent=fal.toLocaleString('ar-SA');$('#benignCases').textContent=viv.toLocaleString('ar-SA');$('#severeCaption').textContent=`${pct(fal,total)} من الحالات المؤهلة`;$('#benignCaption').textContent=`${pct(viv,total)} من الحالات المؤهلة`;$('#latestDate').textContent=dateText(dates[0]);$('#totalCaption').textContent='Vivax · Falciparum · Malariae · Ovale · Mix';const trend=Array(12).fill(0);data.forEach(r=>{const d=excelDate(r[cols.date]);if(d)trend[d.getMonth()]++});draw('#trendChart','line',months,trend,'#087e7b');const cl=topGroups(data,malariaType,5);draw('#classificationChart','doughnut',cl.map(x=>x[0]),cl.map(x=>x[1]),['#087e7b','#d96452','#dcae46','#6689b8','#8a6ca7']);const fac=topGroups(data,r=>val(r,'facility'),10);draw('#facilityChart','bar',fac.map(x=>x[0]),fac.map(x=>x[1]),'#087e7b');let dem;if(demo==='age'){dem=ageBands.map(([label,min,max])=>[label,data.filter(r=>{const a=Number(val(r,'age'));return a>=min&&a<=max}).length]);const unknown=data.filter(r=>!ageBands.some(([,min,max])=>{const a=Number(val(r,'age'));return a>=min&&a<=max})).length;if(unknown)dem.push(['غير متوفر',unknown])}else dem=topGroups(data,r=>val(r,'gender'),5);draw('#demographicChart','bar',dem.map(x=>x[0]),dem.map(x=>x[1]),demo==='age'?'#6689b8':['#087e7b','#d96452','#82929a'],demo==='age');const nat=topGroups(data,r=>val(r,'nationality'),10);draw('#nationalityChart','bar',nat.map(x=>x[0]),nat.map(x=>x[1]),'#dcae46');const peak=trend.indexOf(Math.max(...trend)),other=total-fal-viv;$('#insights').innerHTML=`<p>يعرض هذا الملخص <strong>${total.toLocaleString('ar-SA')}</strong> حالة ضمن المرشحات المحددة. يمثل Falciparum نسبة ${pct(fal,total)} من الحالات، فيما يمثل Vivax ${pct(viv,total)}، وتوزعت النسبة المتبقية ${pct(other,total)} بين الأنواع الأخرى. سجّل <strong>${months[peak]}</strong> أعلى نشاط زمني، ما يستدعي مراجعة أسباب الزيادة ومقارنتها بنمط الفحص والترصد. تصدرت <strong>${fac[0]?.[0]||'—'}</strong> المنشآت المبلغة، بينما كانت جنسية <strong>${nat[0]?.[0]||'—'}</strong> الأكثر ظهورًا. تساعد هذه المؤشرات في ترتيب أولويات المتابعة، ومراجعة جودة التبليغ، وتوجيه التوعية والفحص النشط وفق المنشآت والفئات الأكثر تأثرًا، مع متابعة أي تغيرات أسبوعية قد تشير إلى زيادة غير معتادة.</p>`;renderTable(data)}
function renderTable(data){const pages=Math.max(1,Math.ceil(data.length/PAGE_SIZE));currentPage=Math.min(currentPage,pages);const set=data.slice((currentPage-1)*PAGE_SIZE,currentPage*PAGE_SIZE);$('#caseTable').innerHTML=set.map(r=>`<tr><td>${dateText(excelDate(r[cols.date]))}</td><td>${val(r,'investigation')}</td><td><span class="badge ${malariaType(r)==='Falciparum'?'severe':''}">${malariaType(r)}</span></td><td>${val(r,'facility')}</td><td>${val(r,'age')}</td><td>${val(r,'gender')}</td><td>${val(r,'nationality')}</td><td>${val(r,'status')}</td></tr>`).join('')||'<tr><td colspan="8">لا توجد حالات مطابقة للمرشحات.</td></tr>';$('#tableCount').textContent=`${data.length.toLocaleString('ar-SA')} حالة`;$('#paginationInfo').textContent=`صفحة ${currentPage} من ${pages}`;$('#previousPage').disabled=currentPage===1;$('#nextPage').disabled=currentPage===pages}
function setOptions(id,values){const s=$(id),old=selected(id);s.innerHTML=values.map((v,i)=>`<label><input type="checkbox" value="${String(v).replaceAll('"','&quot;')}" ${old.includes(String(v))?'checked':''}> <span>${v}</span></label>`).join('')}
function prepare(rows){if(!rows.length){alert('لا توجد سجلات في ملف البيانات.');return}cases=rows;const valid=cases.filter(malariaType);setOptions('#monthFilter',months);$('#monthFilter').querySelectorAll('input').forEach((x,i)=>x.value=String(i));setOptions('#facilityFilter',[...new Set(valid.map(r=>val(r,'facility')))].sort());setOptions('#classificationFilter',['Vivax','Falciparum','Malariae','Ovale','Mix']);setOptions('#nationalityFilter',[...new Set(valid.map(r=>val(r,'nationality')))].sort());$('#dataInfo').textContent='';$('#dashboard').hidden=false;$('#dashboard').after($('#uploadPanel'));$('#uploadPanel').classList.add('compact-upload');$('#dataStatus').textContent='البيانات جاهزة محليًا';$('#dataStatus').className='status ready';currentPage=1;render()}
function message(t){$('#uploadMessage').textContent=t}
function parseWorkbook(buffer,label){try{const wb=XLSX.read(buffer,{type:'array',cellDates:true});const name=wb.SheetNames.find(n=>n.toLowerCase()==='sheet1')||wb.SheetNames.find(n=>Object.prototype.hasOwnProperty.call(XLSX.utils.sheet_to_json(wb.Sheets[n],{defval:''})[0]||{},'Investigation'));if(!name)throw new Error('لم يتم العثور على ورقة الحالات');message('');prepare(XLSX.utils.sheet_to_json(wb.Sheets[name],{defval:'',raw:true}))}catch(e){message(`تعذر قراءة الملف: ${e.message}`)}}
function loadFile(file){if(!file)return;message(`جارٍ قراءة ${file.name}…`);const r=new FileReader();r.onload=e=>parseWorkbook(e.target.result,file.name);r.onerror=()=>message('تعذر فتح الملف من الجهاز.');r.readAsArrayBuffer(file)}
$('#fileInput').addEventListener('change',e=>{loadFile(e.target.files[0]);e.target.value=''});$('#replaceFile').onclick=()=>$('#fileInput').click();document.querySelectorAll('.filter-menu>button').forEach(b=>b.onclick=()=>{const menu=b.parentElement;document.querySelectorAll('.filter-menu').forEach(x=>x.classList.toggle('open',x===menu&&!x.classList.contains('open')))});document.addEventListener('click',e=>{if(!e.target.closest('.filter-menu'))document.querySelectorAll('.filter-menu').forEach(x=>x.classList.remove('open'))});['#monthFilter','#facilityFilter','#classificationFilter','#nationalityFilter'].forEach(id=>$(id).addEventListener('change',()=>{currentPage=1;render()}));$('#searchInput').addEventListener('input',()=>{currentPage=1;render()});$('#clearFilters').onclick=()=>{['#monthFilter','#facilityFilter','#classificationFilter','#nationalityFilter'].forEach(id=>$(id).querySelectorAll('input').forEach(o=>o.checked=false));$('#searchInput').value='';currentPage=1;render()};$('#previousPage').onclick=()=>{currentPage--;render()};$('#nextPage').onclick=()=>{currentPage++;render()};document.querySelectorAll('[data-demo]').forEach(b=>b.onclick=()=>{demo=b.dataset.demo;document.querySelectorAll('[data-demo]').forEach(x=>x.classList.toggle('active',x===b));render()});$('#printBtn').onclick=()=>window.print();const dz=$('#dropzone');['dragenter','dragover'].forEach(e=>dz.addEventListener(e,x=>{x.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(e=>dz.addEventListener(e,x=>{x.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>loadFile(e.dataTransfer.files[0]));$('#loadBundled').onclick=async()=>{try{message('جارٍ تحميل الملف…');const x=await fetch('HESN_Investigations2025.xlsx');parseWorkbook(await x.arrayBuffer(),'الملف الموجود بالمجلد')}catch{message('تعذر تحميل الملف الموجود بالمجلد.')}};if(location.protocol.startsWith('http'))$('#loadBundled').click();
