const $ = (s) => document.querySelector(s);
let cases = [], charts = {}, currentPage = 1, demo = 'age';
const PAGE_SIZE = 10;
const cols = {date:'Creation Date',classification:'Malaria Classification',facility:'ReportingOrganizationSource',age:'Age',gender:'Gender',nationality:'Nationality',investigation:'Investigation',status:'Investigation Status'};
const months=['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'];
function val(r,k){const v=r[cols[k]];return v===undefined||v===null||v===''||v==='N/A'?'غير متوفر':String(v).trim()}
function excelDate(v){if(!v||v==='غير متوفر')return null;if(v instanceof Date)return v;if(typeof v==='number')return new Date(Date.UTC(1899,11,30)+v*86400000);const d=new Date(v);return isNaN(d)?null:d}
function dateText(d){return d?new Intl.DateTimeFormat('ar-SA-u-ca-gregory',{day:'numeric',month:'short',year:'numeric'}).format(d):'غير متوفر'}
function norm(s){return String(s||'').toLowerCase().trim()}
function group(data,getter){const out={};data.forEach(r=>{const k=getter(r)||'غير متوفر';out[k]=(out[k]||0)+1});return out}
function top(data,getter,n=10){return Object.entries(group(data,getter)).sort((a,b)=>b[1]-a[1]).slice(0,n)}
function pct(a,b){return b?`${Math.round(a/b*100)}%`:'—'}
function filtered(){const month=$('#monthFilter').value,facility=$('#facilityFilter').value,cls=$('#classificationFilter').value,search=norm($('#searchInput').value);return cases.filter(r=>{const d=excelDate(r[cols.date]);const text=[val(r,'facility'),val(r,'nationality'),val(r,'investigation')].join(' ').toLowerCase();return (month==='all'||(d&&String(d.getMonth())===month))&&(facility==='all'||val(r,'facility')===facility)&&(cls==='all'||val(r,'classification')===cls)&&(!search||text.includes(search))})}
function draw(id,type,labels,data,colors){if(charts[id])charts[id].destroy();charts[id]=new Chart($(id),{type,data:{labels,datasets:[{label:'حالات',data,backgroundColor:colors||'#087e7b',borderColor:colors||'#087e7b',borderWidth:type==='line'?2:0,borderRadius:type==='bar'?6:0,fill:type==='line',tension:.35}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:type==='doughnut',position:'bottom',labels:{font:{family:'IBM Plex Sans Arabic'},padding:16}},tooltip:{rtl:true,bodyFont:{family:'IBM Plex Sans Arabic'},titleFont:{family:'IBM Plex Sans Arabic'}}},scales:type==='doughnut'?{}:{x:{grid:{display:false},ticks:{font:{family:'IBM Plex Sans Arabic'}}},y:{beginAtZero:true,ticks:{precision:0,font:{family:'IBM Plex Sans Arabic'}},grid:{color:'#edf1f0'}}}}})}
function render(){const data=filtered(),total=data.length,severe=data.filter(r=>norm(val(r,'classification')).includes('خبيث')).length,benign=data.filter(r=>norm(val(r,'classification')).includes('حميد')).length,dates=data.map(r=>excelDate(r[cols.date])).filter(Boolean).sort((a,b)=>b-a);$('#totalCases').textContent=total.toLocaleString('ar-SA');$('#severeCases').textContent=severe.toLocaleString('ar-SA');$('#benignCases').textContent=benign.toLocaleString('ar-SA');$('#severeCaption').textContent=`${pct(severe,total)} من إجمالي الحالات`;$('#benignCaption').textContent=`${pct(benign,total)} من إجمالي الحالات`;$('#latestDate').textContent=dateText(dates[0]);$('#totalCaption').textContent='الحالات بعد تطبيق المرشحات';const trend=Array(12).fill(0);data.forEach(r=>{const d=excelDate(r[cols.date]);if(d)trend[d.getMonth()]++});draw('#trendChart','line',months,trend,'#087e7b');const cl=top(data,r=>val(r,'classification'),8);draw('#classificationChart','doughnut',cl.map(x=>x[0]),cl.map(x=>x[1]),['#087e7b','#d96452','#dcae46','#6689b8','#8a6ca7','#64a56f','#82929a']);const fac=top(data,r=>val(r,'facility'),8);draw('#facilityChart','bar',fac.map(x=>x[0]),fac.map(x=>x[1]),'#087e7b');const dem=demo==='age'?top(data,r=>{const a=Number(val(r,'age'));return !a?'غير متوفر':a<5?'0–4':a<15?'5–14':a<30?'15–29':a<45?'30–44':a<60?'45–59':'60+'},7):top(data,r=>val(r,'gender'),5);draw('#demographicChart','bar',dem.map(x=>x[0]),dem.map(x=>x[1]),demo==='age'?'#6689b8':['#087e7b','#d96452','#82929a']);const nat=top(data,r=>val(r,'nationality'),10);draw('#nationalityChart','bar',nat.map(x=>x[0]),nat.map(x=>x[1]),'#dcae46');const peak=trend.indexOf(Math.max(...trend));$('#insights').innerHTML=`<p><strong>${total.toLocaleString('ar-SA')}</strong> حالة ضمن نطاق العرض الحالي.</p><p>أعلى منشأة تسجيلًا: <strong>${fac[0]?.[0]||'—'}</strong>.</p><p>أكثر جنسية مسجلة: <strong>${nat[0]?.[0]||'—'}</strong>، وأعلى نشاط شهري في <strong>${months[peak]}</strong>.</p>`;renderTable(data)}
function renderTable(data){const pages=Math.max(1,Math.ceil(data.length/PAGE_SIZE));currentPage=Math.min(currentPage,pages);const subset=data.slice((currentPage-1)*PAGE_SIZE,currentPage*PAGE_SIZE);$('#caseTable').innerHTML=subset.map(r=>{const c=val(r,'classification'),bad=norm(c).includes('خبيث');return `<tr><td>${dateText(excelDate(r[cols.date]))}</td><td>${val(r,'investigation')}</td><td><span class="badge ${bad?'severe':''}">${c}</span></td><td>${val(r,'facility')}</td><td>${val(r,'age')}</td><td>${val(r,'gender')}</td><td>${val(r,'nationality')}</td><td>${val(r,'status')}</td></tr>`}).join('')||'<tr><td colspan="8">لا توجد حالات مطابقة للمرشحات.</td></tr>';$('#tableCount').textContent=`${data.length.toLocaleString('ar-SA')} حالة`;$('#paginationInfo').textContent=`صفحة ${currentPage} من ${pages}`;$('#previousPage').disabled=currentPage===1;$('#nextPage').disabled=currentPage===pages}
function setOptions(id,values){const s=$(id),old=s.value,label=id==='#monthFilter'?'كل الأشهر':id==='#facilityFilter'?'كل المنشآت':'كل التصنيفات';s.innerHTML=`<option value="all">${label}</option>`+values.map(x=>`<option value="${x.replaceAll('"','&quot;')}">${x}</option>`).join('');s.value=[...s.options].some(o=>o.value===old)?old:'all'}
function prepare(rows){const found=Object.values(cols).filter(c=>Object.prototype.hasOwnProperty.call(rows[0]||{},c));if(!rows.length||found.length<4){alert('لم يتم التعرف على ورقة بيانات الحالات. يرجى اختيار ملف HESN الذي يحتوي على ورقة Sheet1.');return}cases=rows;setOptions('#facilityFilter',[...new Set(cases.map(r=>val(r,'facility')))].sort());setOptions('#classificationFilter',[...new Set(cases.map(r=>val(r,'classification')))].sort());$('#dataInfo').textContent=`تم تحميل ${cases.length.toLocaleString('ar-SA')} سجلًا — ${new Date().toLocaleString('ar-SA')}`;$('#uploadPanel').hidden=true;$('#dashboard').hidden=false;$('#dataStatus').textContent='البيانات جاهزة محليًا';$('#dataStatus').className='status ready';currentPage=1;render()}
function loadFile(file){if(!file)return;if(typeof XLSX==='undefined'||typeof Chart==='undefined'){alert('لم تكتمل مكونات اللوحة. أعد فتح الصفحة من مجلد المشروع بعد تنزيل النسخة المحدّثة.');return}const reader=new FileReader();reader.onload=e=>{try{const wb=XLSX.read(e.target.result,{type:'array',cellDates:true});const name=wb.SheetNames.find(n=>n.toLowerCase()==='sheet1')||wb.SheetNames.find(n=>{const r=XLSX.utils.sheet_to_json(wb.Sheets[n],{defval:''});return r[0]&&Object.prototype.hasOwnProperty.call(r[0],'Investigation')});if(!name)throw new Error('لم يتم العثور على ورقة الحالات');const rows=XLSX.utils.sheet_to_json(wb.Sheets[name],{defval:'',raw:true});prepare(rows)}catch(err){console.error(err);alert(`تعذر قراءة الملف: ${err.message||'تأكد من أنه ملف Excel صالح.'}`)}};reader.readAsArrayBuffer(file)}
$('#fileInput').addEventListener('change',e=>{loadFile(e.target.files[0]);e.target.value=''});$('#replaceFile').onclick=()=>$('#fileInput').click();['#monthFilter','#facilityFilter','#classificationFilter'].forEach(id=>$(id).addEventListener('change',()=>{currentPage=1;render()}));$('#searchInput').addEventListener('input',()=>{currentPage=1;render()});$('#clearFilters').onclick=()=>{['#monthFilter','#facilityFilter','#classificationFilter'].forEach(id=>$(id).value='all');$('#searchInput').value='';currentPage=1;render()};$('#previousPage').onclick=()=>{currentPage--;render()};$('#nextPage').onclick=()=>{currentPage++;render()};document.querySelectorAll('[data-demo]').forEach(b=>b.onclick=()=>{demo=b.dataset.demo;document.querySelectorAll('[data-demo]').forEach(x=>x.classList.toggle('active',x===b));render()});$('#printBtn').onclick=()=>window.print();const dz=$('#dropzone');['dragenter','dragover'].forEach(e=>dz.addEventListener(e,x=>{x.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(e=>dz.addEventListener(e,x=>{x.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>loadFile(e.dataTransfer.files[0]));
